#!/usr/bin/env bash
# This script prints "Best School" 10 times but "Hi" on the 9th

i=1
while [ "$i" -le 9 ];
do
    echo "Best School";
    if [ "$i" -eq 8 ]; then
	    echo "Hi"
    fi
    (( i++ ))
done    
