#!/usr/bin/env bash
# The script displays: "bad luck" 4th iteration, "good luck" 8th, and "Best School" all others

i=1
while [ "$i" -le 10 ]
do 
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done   
