#!/usr/bin/env bash
# This script prints 1-20 where 4 then "bad luck from China 4th iteration, 9 then bad luck from Japan for the 9th, 17 then bad luck from italy for the 17th

i=1
while [ "$i" -le 20 ]
do
    echo "$i" 
    case $i in
	    4) echo "bad luck from China" ;;
            9) echo "bad luck from Japan" ;;
	    17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done    
